emissions/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    path('', EmissionListView.as_view(), name='emission-list'),
    path('archived', ArchivedEmissionsListView.as_view(), name='emission-archived-list'),
    path('categories', CategoryListView.as_view(), name='category-list'),
    path('days', DaysView.as_view(), name='days'),
    path('add', EmissionCreateView.as_view(), name='emission-add'),
    re_path(r'^upload/(?P<transaction_id>[a-zA-Z0-9-]+)/$', UploadView.as_view(), name='upload'),
    path('news/', NewsListView.as_view(), name='news-list'),
    re_path(r'^news/(?P<slug>[\w,-]+)/$', NewsItemDetailView.as_view(), name='newsitem-view'),
    re_path(r'^news/(?P<slug>[\w,-]+)/delete$', NewsItemDeleteView.as_view(), name='newsitem-delete'),
    re_path(r'^news/(?P<slug>[\w,-]+)/edit$', NewsItemUpdateView.as_view(), name='newsitem-update'),
    path('add-newsitem', NewsItemAddView.as_view(), name='newsitem-add'),
    path('manage/categories/', CategoryManageView.as_view(), name='emission-categories-manage'),
    path('manage/categories/add/', CategoryManageAddView.as_view(), name='emission-categories-manage-add'),
    path(
        'manage/categories/edit/<int:pk>/',
        CategoryManageEditView.as_view(),
        name='emission-categories-manage-edit',
    ),
    path(
        'manage/categories/delete/<int:pk>/',
        CategoryManageDeleteView.as_view(),
        name='emission-categories-manage-delete',
    ),
    path('manage/news-categories/', NewsCategoryManageView.as_view(), name='emission-news-categories-manage'),
    path(
        'manage/news-categories/add/',
        NewsCategoryManageAddView.as_view(),
        name='emission-news-categories-manage-add',
    ),
    path(
        'manage/news-categories/edit/<int:pk>/',
        NewsCategoryManageEditView.as_view(),
        name='emission-news-categories-manage-edit',
    ),
    path(
        'manage/news-categories/delete/<int:pk>/',
        NewsCategoryManageDeleteView.as_view(),
        name='emission-news-categories-manage-delete',
    ),
    path('manage/formats/', FormatManageView.as_view(), name='emission-formats-manage'),
    path('manage/formats/add/', FormatManageAddView.as_view(), name='emission-formats-manage-add'),
    path(
        'manage/formats/edit/<int:pk>/',
        FormatManageEditView.as_view(),
        name='emission-formats-manage-edit',
    ),
    path(
        'manage/formats/delete/<int:pk>/',
        FormatManageDeleteView.as_view(),
        name='emission-formats-manage-delete',
    ),
    re_path(r'^(?P<slug>[\w,-]+)/$', EmissionDetailView.as_view(), name='emission-view'),
    re_path(r'^(?P<slug>[\w,-]+)/edit/$', EmissionUpdateView.as_view(), name='emission-update'),
    re_path(r'^(?P<slug>[\w,-]+)/delete/$', EmissionDeleteView.as_view(), name='emission-delete'),
    re_path(
        r'^(?P<slug>[\w,-]+)/add-schedule$', EmissionAddScheduleView.as_view(), name='emission-add-schedule'
    ),
    re_path(
        r'^(?P<slug>[\w,-]+)/add-absence$', EmissionAddAbsenceView.as_view(), name='emission-add-absence'
    ),
    re_path(r'^(?P<slug>[\w,-]+)/chat/open/$', EmissionOpenChatView.as_view(), name='emission-open-chat'),
    re_path(r'^(?P<slug>[\w,-]+)/chat/close/$', EmissionCloseChatView.as_view(), name='emission-close-chat'),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/schedule/(?P<pk>\d+)/edit$',
        ScheduleUpdateView.as_view(),
        name='schedule-edit',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/schedule/(?P<pk>\d+)/remove$',
        ScheduleDeleteView.as_view(),
        name='schedule-delete',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/absence/(?P<pk>\d+)/remove$',
        AbsenceDeleteView.as_view(),
        name='absence-delete',
    ),
    re_path(r'^(?P<emission_slug>[\w,-]+)/add$', EpisodeCreateView.as_view(), name='episode-add'),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/$', EpisodeDetailView.as_view(), name='episode-view'
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/edit/$',
        EpisodeUpdateView.as_view(),
        name='episode-update',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/delete/$',
        EpisodeDeleteView.as_view(),
        name='episode-delete',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/start/$',
        EpisodeStartView.as_view(),
        name='episode-start',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/stop/$',
        EpisodeStopView.as_view(),
        name='episode-stop',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/add-soundfile$',
        EpisodeAddSoundFileView.as_view(),
        name='episode-add-soundfile',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/add-diffusion$',
        EpisodeAddDiffusionView.as_view(),
        name='episode-add-diffusion',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/diffusion/(?P<pk>\d+)/remove$',
        DiffusionDeleteView.as_view(),
        name='diffusion-delete',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/sounds/(?P<pk>\d+)/remove$',
        SoundFileDeleteView.as_view(),
        name='soundfile-delete',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/sounds/(?P<pk>\d+)/$',
        SoundFileUpdateView.as_view(),
        name='soundfile-update',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/sounds/update-order$',
        EpisodeSoundFilesUpdateOrderView.as_view(),
        name='episode-soundfiles-update-order',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/regie/$',
        EpisodeRegieView.as_view(),
        name='episode-regie',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/regie/marks/$',
        EpisodeRegieMarks.as_view(),
        name='episode-regie-marks',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/regie/delete/$',
        EpisodeRegieDeleteElementView.as_view(),
        name='episode-regie-delete-element',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/regie/update-order$',
        EpisodeRegieUpdateOrderView.as_view(),
        name='episode-regie-update-order',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/add-newsitem$',
        EmissionNewsItemAdd.as_view(),
        name='emission-newsitem-add',
    ),
    re_path(
        r'^category/(?P<slug>[\w,-]+)/add-newsitem$', CategoryNewsItemAddView.as_view(), name='newsitem-add'
    ),
    # images
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/pictures-order/$',
        EpisodePicturesOrderView.as_view(),
        name='episode-pictures-order',
    ),
    re_path(
        r'^(?P<emission_slug>[\w,-]+)/(?P<slug>[\w,-]+)/add-picture/$',
        EpisodePictureAddView.as_view(),
        name='episode-picture-add',
    ),
    path(
        'manage/images/edit/<int:pk>/',
        PictureEditView.as_view(),
        name='picture-edit',
    ),
    path(
        'manage/images/delete/<int:pk>/',
        PictureDeleteView.as_view(),
        name='picture-delete',
    ),
]

emissions/models.py
import datetime
import json
import os
import statistics
import urllib.parse

from ckeditor.fields import RichTextField
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import URLValidator
from django.db import models
from django.db.models import Q
from django.db.models.expressions import RawSQL
from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch.dispatcher import receiver
from django.forms import fields
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import is_aware, make_naive
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _
from django.utils.translation import pgettext_lazy
from taggit.managers import TaggableManager

from .app_settings import app_settings
from .utils import get_duration, maybe_resize

LICENSES = (
    ('', _('Unspecified')),
    ('cc by', _('Creative Commons Attribution')),
    ('cc by-sa', _('Creative Commons Attribution ShareAlike')),
    ('cc by-nc', _('Creative Commons Attribution NonCommercial')),
    ('cc by-nd', _('Creative Commons Attribution NoDerivs')),
    ('cc by-nc-sa', _('Creative Commons Attribution NonCommercial ShareAlike')),
    ('cc by-nc-nd', _('Creative Commons Attribution NonCommercial NoDerivs')),
    ('cc0 / pd', _('Creative Commons Zero / Public Domain')),
    ('artlibre', _('Art Libre')),
)

PODCAST_SOUND_QUALITY_LIST = (
    ('standard', _('Standard')),
    ('high', _('High')),
    ('highest', _('Highest')),
)


def get_first_url_from_multi(value):
    if not value:
        return None
    return value.splitlines()[0]


def get_url_kind(url):
    netloc = urllib.parse.urlparse(url).netloc
    if netloc in ('facebook.com', 'www.facebook.com'):
        return 'facebook'
    if netloc in ('t.co', 'twitter.com'):
        return 'twitter'
    if netloc in ('instagram.com', 'www.instagram.com'):
        return 'instagram'
    if netloc in ('twitch.com', 'twitch.tv', 'www.twitch.com', 'www.twitch.tv'):
        return 'twitch'
    if netloc == 'www.youtube.com':
        return 'youtube'
    if netloc.endswith('.bandcamp.com'):
        return 'bandcamp'
    if netloc in ('soundcloud.com', 'on.soundcloud.com'):
        return 'soundcloud'
    if netloc == 'www.mixcloud.com':
        return 'mixcloud'
    return None


def get_urls_and_kind(value):
    for url in (value or '').splitlines():
        yield (get_url_kind(url), url)


def get_urls_by_kind(value):
    urls = []
    for url in (value or '').splitlines():
        kind = get_url_kind(url) or '_website'
        urls.append((kind, url))
    urls.sort()
    urls = [(x.strip('_'), y) for x, y in urls]
    return urls


def generate_slug(instance, **query_filters):
    base_slug = instance.base_slug
    slug = base_slug
    i = 1

    # no optimization: check slug in DB each time
    while instance._meta.model.objects.filter(slug=slug, **query_filters).exists():
        slug = '%s-%s' % (base_slug, i)
        i += 1
    return slug


class WeekdayMixin:
    def get_weekday(self):
        weekday = self.datetime.weekday() + 7
        if self.datetime.time() < datetime.time(app_settings.DAY_HOUR_START, app_settings.DAY_MINUTE_START):
            weekday -= 1
        weekday %= 7
        return weekday

    def is_on_weekday(self, day):  # day is [1..7]
        week_day = self.datetime.weekday()
        if (self.datetime.hour, self.datetime.minute) <= (
            app_settings.DAY_HOUR_START,
            app_settings.DAY_MINUTE_START,
        ):
            week_day -= 1
        week_day = (week_day % 7) + 1
        if hasattr(self, 'episode'):
            if (self.datetime.hour, self.datetime.minute) <= (
                app_settings.DAY_HOUR_START,
                app_settings.DAY_MINUTE_START,
            ) and (
                self.end_datetime.hour,
                self.end_datetime.minute,
            ) > (
                app_settings.DAY_HOUR_START,
                app_settings.DAY_MINUTE_START,
            ):
                if (self.end_datetime.weekday() + 1) == day:
                    return True
        return week_day == day


class CategoryManager(models.Manager):
    def get_by_natural_key(self, key):
        try:
            return self.get(slug=key)
        except ObjectDoesNotExist:
            return self.get(id=key)


class Category(models.Model):
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['title']

    title = models.CharField(_('Title'), max_length=50)
    slug = models.SlugField(null=True)
    itunes_category = models.CharField(_('iTunes Category Name'), max_length=100, null=True, blank=True)
    archived = models.BooleanField(pgettext_lazy('category', 'Archived'), default=False)

    objects = CategoryManager()

    def natural_key(self):
        return (self.slug,) if self.slug else (self.id,)

    def sorted_emission(self):
        return self.emission_set.order_by('title')

    def __str__(self):
        return self.title


class Format(models.Model):
    class Meta:
        verbose_name = _('Format')
        verbose_name_plural = _('Formats')
        ordering = ['title']

    title = models.CharField(_('Title'), max_length=50)
    slug = models.SlugField(null=True)
    archived = models.BooleanField(pgettext_lazy('format', 'Archived'), default=False)

    def __str__(self):
        return self.title


def get_image_path(instance, filename):
    if isinstance(instance, Emission):
        return os.path.join('images', instance.slug, os.path.basename(filename))
    if isinstance(instance, Nonstop):
        return os.path.join('images', 'nonstop', instance.slug, os.path.basename(filename))
    if isinstance(instance, Episode):
        return os.path.join('images', instance.emission.slug, os.path.basename(filename))
    if isinstance(instance, NewsItem):
        return os.path.join('images', 'news', instance.slug, os.path.basename(filename))
    if isinstance(instance, Picture):
        return get_image_path(instance.get_content_object(), filename)


class MultiURLField(models.TextField):
    def validate(self, value, model_instance):
        super().validate(value, model_instance)
        url_validator = URLValidator(schemes=('http', 'https'))
        for line in (value or '').splitlines():
            url_validator(line)


class Emission(models.Model):
    class Meta:
        verbose_name = _('Emission')
        verbose_name_plural = _('Emissions')
        ordering = ['title']

    title = models.CharField(_('Title'), max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    subtitle = models.CharField(_('Subtitle'), max_length=80, null=True, blank=True)
    text = RichTextField(_('Description'), null=True)
    archived = models.BooleanField(pgettext_lazy('emission', 'Archived'), default=False)
    categories = models.ManyToManyField(Category, verbose_name=_('Categories'), blank=True)

    # XXX: languages (models.ManyToManyField(Language))

    duration = models.IntegerField(_('Duration'), default=60, help_text=_('In minutes'))

    default_license = models.CharField(
        _('Default license for podcasts'), max_length=20, blank=True, default='', choices=LICENSES
    )
    podcast_sound_quality = models.CharField(
        _('Podcast sound quality'), max_length=20, default='standard', choices=PODCAST_SOUND_QUALITY_LIST
    )
    email = models.EmailField(_('Email'), max_length=254, null=True, blank=True)
    website = MultiURLField(_('Website'), null=True, blank=True)

    image_usage_ok = models.BooleanField(_('Include image'), default=False)
    image = models.ImageField(_('Image'), upload_to=get_image_path, max_length=250, null=True, blank=True)
    image_attribution_text = models.CharField(
        _('Text for image attribution'), max_length=250, null=True, blank=True
    )
    image_attribution_url = models.URLField(_('URL for image attribution'), null=True, blank=True)
    tags = TaggableManager(_('Tags'), blank=True)

    chat_open = models.DateTimeField(null=True, blank=True)

    # denormalized from Focus
    got_focus = models.DateTimeField(default=None, null=True, blank=True)
    has_focus = models.BooleanField(default=False)

    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    last_update_timestamp = models.DateTimeField(auto_now=True, null=True)

    def get_absolute_url(self):
        return reverse('emission-view', kwargs={'slug': str(self.slug)})

    def __str__(self):
        return self.title

    @property
    def base_slug(self):
        return slugify(self.title).strip('-') or 'untitled'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_slug(self)
        super().save(*args, **kwargs)
        if self.id is not None and self.image:
            maybe_resize(self.image.path)

    def get_recurring_content(self):
        from nonstop.models import RecurringPlaylistDiffusion, RecurringStreamDiffusion

        recurring_stream = RecurringStreamDiffusion.objects.filter(schedule__in=self.schedule_set.all())
        if recurring_stream.exists():
            return recurring_stream
        recurring_playlist = RecurringPlaylistDiffusion.objects.filter(schedule__in=self.schedule_set.all())
        if recurring_playlist.exists():
            return recurring_playlist

    def get_week_compacted_schedules(self, rerun=None):
        schedules = [
            x
            for x in self.schedule_set.all().order_by('datetime')
            if x.is_current() and ((rerun is None and True) or x.rerun is rerun)
        ]
        if len(schedules) > 1 and len({x.datetime for x in schedules}) == 1:
            # multiple schedules for same day/hour, must be a custom week combination,
            # alter first schedule week bits
            for schedule in schedules[1:]:
                schedules[0].weeks |= schedule.weeks

emissions/templates/emissions/absence_form.html
{% extends "base.html" %}
{% load gadjo i18n %}

{% block appbar %}
  <h2>{% trans "Absence" %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    <div id="form-content">
      {% csrf_token %}
      {{ form|with_template }}
    </div>
    {% block buttons %}
      <div class="buttons">
        <button>{% trans "Add this absence" %}</button>
        <a class="cancel" href="..">{% trans "Cancel" %}</a>
      </div>
    {% endblock %}
  </form>
{% endblock %}

emissions/templates/emissions/category_list.html
{% extends "emissions/emission_list.html" %}
{% load i18n %}

{% block content %}

  {% for category in object_list %}
    <div class="section">
      <h3>{{ category.title }}</h3>

      <ul class="emission-list">
        {% for emission in category.sorted_emission %}
          {% if not emission.archived %}
            <li><a href="{{ emission.slug }}/">{{ emission.title }}</a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>

  {% endfor %}

{% endblock %}

emissions/templates/emissions/days.html
{% extends "emissions/emission_list.html" %}
{% load i18n %}

{% block content %}

  {% for day in days %}
    <div class="section">
      <h3>{{ day.datetime|date:"l" }}</h3>

      <ul class="emission-list">
        {% for schedule in day.schedules %}
          <li><a href="{{ schedule.emission.slug }}/">
            <span class="emission--schedule">{{ schedule.datetime|date:"H:i" }}</span>
            <span class="emission--name">{{ schedule.emission.title }}</span></a></li>
        {% endfor %}
      </ul>
    </div>

  {% endfor %}

{% endblock %}

emissions/templates/emissions/emission_base.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Emissions" %} | {{ block.super }}{% endblock %}

{% block breadcrumb-links %}
  {{ block.super }}
  <a class="button" href="{% url 'emission-list' %}">{% trans "Emissions" %}</a>
{% endblock %}

emissions/templates/emissions/emission_detail.html
{% extends "emissions/emission_base.html" %}
{% load gadjo i18n %}

{% block page-title %}{{ emission.title }} | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>{{ emission.title }}
    {% for category in emission.categories.all %}
      {% if forloop.first %} - {% endif %}
      <small><i>{{ category.title }} </i></small>
    {% endfor %}
  </h2>
{% endblock %}

{% block content %}

  <div class="bo-block">
    {% if emission.subtitle %}
      <div class="description">
        {{ emission.subtitle|safe }}
      </div>
    {% endif %}

    {% if emission.image %}
      <div class="image">
        <img src="{{ emission.image.url }}"/>
      </div>
    {% endif %}

    {% if emission.text %}
      {{ emission.text|safe }}
    {% endif %}

    {% if emission.website %}
      <ul class="websites">
        {% for kind, url in emission.get_website_urls.items %}
          <li><a href="{{ url }}">{{ url }}</a></li>
        {% endfor %}
      </ul>
    {% endif %}

    {% if emission.email %}
      <ul class="email">
        <li>{% trans "Email:" %} <a href="mailto:{{ emission.email }}">{{ emission.email }}</a></li>
      </ul>
    {% endif %}

  </div>

  {% if emission.user_set.count > 0 %}
    <div class="bo-block team">
      <h3>{% trans "Team:" %}</h3>
      <ul class="team">
        {% for member in emission.user_set.all %}
          <li><a href="mailto:{{member.email}}">{{member}}</a></li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <div class="bo-block two-columns schedule-team">

    <div>
      <h3>{% trans "Schedules" %}</h3>

      {% if schedules or future_schedules %}
        <ul>
          {% for schedule in schedules %}
            {% include "includes/schedule_list_item.html" %}
          {% endfor %}
          {% for schedule in future_schedules %}
            {% include "includes/schedule_list_item.html" with future=True %}
          {% endfor %}
        </ul>
      {% endif %}
      {% if past_schedules %}
        {% if schedules or future_schedules %}
          <details>
            <summary>{% trans "Past schedules" %}</summary>
        {% endif %}
        <ul>
          {% for schedule in past_schedules %}
            {% include "includes/schedule_list_item.html" with past=True %}
          {% endfor %}
        </ul>
        {% if schedules or future_schedules %}
          </details>
        {% endif %}
      {% endif %}

      {% if schedules and not schedules_without_reruns %}
        <div class="pk-error">{% trans "An emission cannot have only rerun schedules." %}</div>
      {% endif %}
    </div>

    <div>
      {% if absences %}
        <h3>{% trans "Planned absences" %}</h3>

        <ul>
          {% for absence in absences %}
            <li>{{ absence.datetime }}
              {% if can_manage %}
                <a href="absence/{{ absence.id }}/remove" class="icon-remove-sign" title="Retirer"></a>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <br style="clear: both;"/>
  </div>

  {% with recurring=emission.get_recurring_content.0 %}
    {% if recurring %}
      <div class="bo-block recurring-content">
        <p>
          <strong>{% trans "Content:" %}</strong>
          {{ recurring.description }}
        </p>
      </div>
    {% endif %}
  {% endwith %}

  <form id="add-schedule-form" action="add-schedule" method="POST" style="display: none;">
    {% csrf_token %}
    {{ add_schedule_form|with_template }}
    <div class="buttons">
      <button>{% trans "Add this schedule" %}</button>
    </div>
  </form>

  <div class="bo-block two-columns">

    <div>
      <h3>{% trans "Episodes" %}</h3>

      <ul class="episode-list">
        {% for episode in episodes %}
          <li>{{ episode.first_diffusion|date:"d E o H:i"|lower }}
            <br/>   <a href="{{ episode.slug }}/">{{ episode.title }}</a>
            {% if episode.image %}<span class="icon-image"></span>{%endif%}
            {% if episode.has_sound %}<span class="icon-music"></span>{%endif%}
          </li>
        {% endfor %}
      </ul>
    </div>

    <div>
      <h3>{% trans "Newsitems" %}</h3>

      <ul class="episode-list">
        {% for newsitem in newsitems %}
          <li>{{ newsitem.date|date:"d E o"|lower }}
            <a href="{% url 'newsitem-view' slug=newsitem.slug %}">{{ newsitem.title }}</a>
          </li>
        {% empty %}
          {% trans "No newsitems." %}
        {% endfor %}
      </ul>
    </div>

    <br style="clear: both;"/>
  </div> <!-- .two-columns -->

  {% if newsitems.count >= 10 or episodes.count >= 10 %}
    <p><a href="?all">{% trans "Display page with all episodes an newsitems" %}</a></p>
  {% endif %}

{% endblock %}

{% block sidebar %}
  <aside id="sidebar">

    <ul class="sidebar-buttons">
      {% include "includes/button-view-online.html" with object=emission %}
    </ul>

    <h3>{% trans "Actions" %}</h3>
    <ul class="sidebar-buttons">
      {% if can_manage %}
        <li><a class="button" href="{% url 'episode-add' emission_slug=emission.slug %}">{% trans "Add an episode" %}</a></li>
        <li><a class="button" href="{% url 'emission-newsitem-add' emission_slug=emission.slug %}">{% trans "Add a newsitem" %}</a></li>
        <li><a class="button" href="{% url 'emission-update' slug=emission.slug %}">{% trans "Edit emission details" %}</a></li>
        {% if perms.emissions.change_schedule %}
          <li><a class="button" id="add-schedule-link" rel="popup" href="{% url 'emission-add-schedule' slug=emission.slug %}">{% trans "Add schedule" %}</a></li>
        {% endif %}
        {% if schedules %}
          <li><a class="button" id="add-absence-link" rel="popup" href="{% url 'emission-add-absence' slug=emission.slug %}">{% trans "Add absence" %}</a></li>
        {% endif %}
        {% if has_emission_chats %}
          {% if emission.chat_open %}
            <li><a class="button" href="{% url 'emission-close-chat' slug=emission.slug %}">{% trans "Close chat" %}</a></li>
          {% else %}
            <li><a class="button" href="{% url 'emission-open-chat' slug=emission.slug %}">{% trans "Open chat" %}</a></li>
          {% endif %}
        {% endif %}

        {% if has_soma and perms.nonstop_add_recurringoccurence and schedules_without_reruns %}
          <li><a class="button" href="{% url 'nonstop-recurring-stuff' slug=object.slug %}">{% trans "Manage recurring content" %}</a></li>
        {% endif %}

        {% include "includes/button-focus.html" with object=emission %}

        {% if perms.emissions.delete_emission %}
          <li><a class="button delete-button" rel="popup" href="delete/">{% trans "Delete" %}</a></li>
        {% endif %}
      {% endif %}
    </ul>

  </aside>
{% endblock %}

{% block page-end %}
  <script>
    $(function() {
      $('.image img').click(function() { $(this).toggleClass('large'); });
    });
  </script>
{% endblock %}

emissions/templates/emissions/news_base.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Newsitems" %} | {{ block.super }}{% endblock %}

{% block breadcrumb-links %}
  {{ block.super }}
  <a class="button" href="{% url 'news-list' %}">{% trans "Newsitems" %}</a>
{% endblock %}

emissions/templates/emissions/newsitem_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{{ object.datetime|date:"d E o"|lower }} - {{ object.title }}</h2>
  <span class="actions"><a href="{% url 'home' %}">{% trans "Back to home" %}</a></span>
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <p>
      {% trans "Are you sure you want to delete this newsitem?" %}
    </p>
    <div class="buttons">
      <button class="delete-button">{% trans "Confirm Deletion" %}</button>
      <a class="cancel" href="..">{% trans "Cancel" %}</a>
    </div>
  </form>


{% endblock %}